# Generated by Django 4.1.3 on 2025-01-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserImageRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(upload_to='')),
                ('final_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('recognized_emotion', models.CharField(blank=True, max_length=20, null=True)),
                ('predicted_emotions', models.CharField(blank=True, max_length=155, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('COM', 'Complete'), ('ERR', 'Error')], default='PEN', max_length=3)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
